export const genresConfig = [
  { name: 'Боевик', value: 'боевик' },
  { name: 'Детский', value: 'детский' },
  { name: 'Документальный', value: 'документальный' },
  { name: 'Драма', value: 'драма' },
  { name: 'Игра', value: 'игра' },
  { name: 'Короткометражка', value: 'короткометражка' },
  { name: 'Комедия', value: 'комедия' },
  { name: 'Мультфильм', value: 'мультфильм' },
  { name: 'Музыка', value: 'музыка' },
  { name: 'Приключения', value: 'приключения' },
  { name: 'Реальное ТВ', value: 'реальное, ТВ' },
  { name: 'Семейный', value: 'семейный' },
  { name: 'Триллер', value: 'триллер' },
  { name: 'Ужасы', value: 'ужасы' },
  { name: 'Фантастика', value: 'фантастика' },
  { name: 'Фэнтези', value: 'фэнтези' },
];

export const countriesConfig = [
  { name: 'Беларусь', value: 'Беларусь' },
  { name: 'Германия', value: 'Германия' },
  { name: 'Египет', value: 'Египет' },
  { name: 'Китай', value: 'Китай' },
  { name: 'Россия', value: 'Россия' },
  { name: 'США', value: 'США' },
  { name: 'Швеция', value: 'Швеция' },
  { name: 'Япония', value: 'Япония' },
];

export const yearsConfig = [
  { name: '2000', value: '2000' },
  { name: '2001', value: '2001' },
  { name: '2002', value: '2002' },
  { name: '2003', value: '2003' },
  { name: '2004', value: '2004' },
  { name: '2005', value: '2005' },
  { name: '2006', value: '2006' },
  { name: '2007', value: '2007' },
  { name: '2008', value: '2008' },
  { name: '2009', value: '2009' },
  { name: '2010', value: '2010' },
  { name: '2011', value: '2011' },
  { name: '2012', value: '2012' },
  { name: '2013', value: '2013' },
  { name: '2014', value: '2014' },
  { name: '2015', value: '2015' },
  { name: '2016', value: '2016' },
  { name: '2017', value: '2017' },
  { name: '2018', value: '2018' },
  { name: '2019', value: '2019' },
  { name: '2020', value: '2020' },
  { name: '2021', value: '2021' },
  { name: '2022', value: '2022' },
  { name: '2023', value: '2023' },
  { name: '2024', value: '2024' },
];

export const ratingsConfig = [
  { name: 'Кинопоиск', value: '7-10' },
  { name: 'IMDB', value: '7-10' },
  { name: 'TMDB', value: '7-10' },
  { name: 'MPAA', value: '7-10' },
];
