export const helpData = {
  docs: [
    {
      id: 6399111,
      name: 'Абсолютный хищник',
      alternativeName: 'The Bayou',
      enName: null,
      type: 'movie',
      typeNumber: 1,
      year: null,
      description:
        'В живописных лесах Луизианы терпит крушение небольшой пассажирский самолет. Помощи ждать неоткуда, мобильная связь мертва. Единственный путь к спасению пролегает через болотистую местность, где обитают аллигаторы. У них агрессивный нрав, высокая подвижность и отменный аппетит. И кажется, уже ничто не в силах испортить им трапезу.',
      shortDescription: null,
      status: 'post-production',
      rating: {
        kp: 0,
        imdb: 0,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      votes: {
        kp: 0,
        imdb: 0,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      movieLength: null,
      totalSeriesLength: null,
      seriesLength: null,
      ratingMpaa: null,
      ageRating: null,
      poster: {
        url: 'https://image.openmoviedb.com/kinopoisk-images/10768063/0147b4ee-236c-4a07-8828-d0d3108f7f9c/orig',
        previewUrl:
          'https://image.openmoviedb.com/kinopoisk-images/10768063/0147b4ee-236c-4a07-8828-d0d3108f7f9c/x1000',
      },
      genres: [
        {
          name: 'триллер',
        },
      ],
      countries: [
        {
          name: 'Великобритания',
        },
      ],
      top10: null,
      top250: null,
      isSeries: false,
      ticketsOnSale: false,
    },
    {
      id: 6403886,
      name: 'ДДТ XX век',
      alternativeName: 'DDT XX vek',
      type: 'tv-series',
      typeNumber: 2,
      year: null,
      description: null,
      shortDescription: null,
      status: null,
      rating: {
        kp: 0,
        imdb: 0,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      votes: {
        kp: 0,
        imdb: 0,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      movieLength: null,
      totalSeriesLength: null,
      seriesLength: null,
      ratingMpaa: null,
      ageRating: null,
      releaseYears: [
        {
          start: null,
          end: null,
        },
      ],
      top10: null,
      top250: null,
      isSeries: true,
      ticketsOnSale: false,
    },
    {
      id: 6399097,
      name: 'Гибернация',
      alternativeName: null,
      enName: null,
      type: 'movie',
      typeNumber: 1,
      year: null,
      description: null,
      shortDescription: null,
      status: null,
      rating: {
        kp: 0,
        imdb: 0,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      votes: {
        kp: 0,
        imdb: 0,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      movieLength: null,
      totalSeriesLength: null,
      seriesLength: null,
      ratingMpaa: null,
      ageRating: 18,
      genres: [
        {
          name: 'короткометражка',
        },
      ],
      countries: [
        {
          name: 'Россия',
        },
      ],
      top10: null,
      top250: null,
      isSeries: false,
      ticketsOnSale: false,
    },
    {
      id: 6399762,
      name: 'Золотой дубль',
      alternativeName: null,
      enName: null,
      type: 'movie',
      typeNumber: 1,
      year: null,
      description:
        'Легендарный спартаковец Никита Симонян становится тренером ереванского «Арарата» и ставит перед собой невыполнимую задачу: нацеливается на «золотой дубль» — медаль чемпионата и победу в Кубке СССР — но команда не принимает нового тренера, а главный противник готов на все ради победы.',
      shortDescription: null,
      status: null,
      rating: {
        kp: 0,
        imdb: 0,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      votes: {
        kp: 0,
        imdb: 0,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      movieLength: null,
      totalSeriesLength: null,
      seriesLength: null,
      ratingMpaa: null,
      ageRating: null,
      genres: [
        {
          name: 'спорт',
        },
        {
          name: 'драма',
        },
      ],
      countries: [
        {
          name: 'Россия',
        },
      ],
      top10: null,
      top250: null,
      isSeries: false,
      ticketsOnSale: false,
    },
    {
      id: 6396262,
      name: 'Свободное время',
      alternativeName: null,
      type: 'tv-series',
      typeNumber: 2,
      year: 2014,
      description: null,
      shortDescription: null,
      status: null,
      rating: {
        kp: 0,
        imdb: 0,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      votes: {
        kp: 1,
        imdb: 0,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      movieLength: null,
      totalSeriesLength: null,
      seriesLength: null,
      ratingMpaa: null,
      ageRating: null,
      genres: [
        {
          name: 'документальный',
        },
      ],
      countries: [
        {
          name: 'Россия',
        },
      ],
      releaseYears: [
        {
          start: 2014,
          end: null,
        },
      ],
      top10: null,
      top250: null,
      isSeries: true,
      ticketsOnSale: false,
    },
    {
      id: 6399777,
      name: 'История одного полёта',
      alternativeName: null,
      enName: null,
      type: 'movie',
      typeNumber: 1,
      year: null,
      description: null,
      shortDescription: null,
      status: null,
      rating: {
        kp: 0,
        imdb: 0,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      votes: {
        kp: 0,
        imdb: 0,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      movieLength: null,
      totalSeriesLength: null,
      seriesLength: null,
      ratingMpaa: null,
      ageRating: null,
      genres: [
        {
          name: 'короткометражка',
        },
        {
          name: 'драма',
        },
        {
          name: 'комедия',
        },
      ],
      countries: [
        {
          name: 'Россия',
        },
      ],
      top10: null,
      top250: null,
      isSeries: false,
      ticketsOnSale: false,
    },
    {
      id: 6396260,
      name: 'Несправедливость. И как с ней бороться',
      alternativeName: null,
      type: 'tv-series',
      typeNumber: 2,
      year: 2010,
      description:
        'Программа социально-правовой тематики, целью которой является фиксирование, либо инициирование справедливого решения конфликтной ситуации между героями.',
      shortDescription: null,
      status: null,
      rating: {
        kp: 0,
        imdb: 0,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      votes: {
        kp: 1,
        imdb: 0,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      movieLength: null,
      totalSeriesLength: null,
      seriesLength: null,
      ratingMpaa: null,
      ageRating: null,
      genres: [
        {
          name: 'реальное ТВ',
        },
        {
          name: 'ток-шоу',
        },
      ],
      countries: [
        {
          name: 'Россия',
        },
      ],
      releaseYears: [
        {
          start: 2010,
          end: null,
        },
      ],
      top10: null,
      top250: null,
      isSeries: true,
      ticketsOnSale: false,
    },
    {
      id: 6396263,
      name: 'Хватит молчать',
      alternativeName: null,
      type: 'tv-series',
      typeNumber: 2,
      year: 2011,
      description:
        'Программа помогает узнать, что думают и делают другие в проблемных повседневных ситуациях и какие полезные советы могут дать эксперты.',
      shortDescription: null,
      status: null,
      rating: {
        kp: 0,
        imdb: 0,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      votes: {
        kp: 1,
        imdb: 0,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      movieLength: null,
      totalSeriesLength: null,
      seriesLength: null,
      ratingMpaa: null,
      ageRating: null,
      genres: [
        {
          name: 'реальное ТВ',
        },
      ],
      countries: [
        {
          name: 'Россия',
        },
      ],
      releaseYears: [
        {
          start: 2011,
          end: null,
        },
      ],
      top10: null,
      top250: null,
      isSeries: true,
      ticketsOnSale: false,
    },
    {
      id: 6396515,
      name: 'Коллекция глупостей Максима Кононенко',
      alternativeName: null,
      type: 'tv-series',
      typeNumber: 2,
      year: 2009,
      description:
        'Подборка необъяснимых проявлений маразма и всплесков идиотизма у мелких чиновников, правоохранителей и обывателей.',
      shortDescription: null,
      status: 'completed',
      rating: {
        kp: 0,
        imdb: 0,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      votes: {
        kp: 1,
        imdb: 0,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      movieLength: null,
      totalSeriesLength: null,
      seriesLength: null,
      ratingMpaa: null,
      ageRating: null,
      genres: [
        {
          name: 'реальное ТВ',
        },
        {
          name: 'комедия',
        },
      ],
      countries: [
        {
          name: 'Россия',
        },
      ],
      releaseYears: [
        {
          start: 2009,
          end: 2014,
        },
      ],
      top10: null,
      top250: null,
      isSeries: true,
      ticketsOnSale: false,
    },
    {
      id: 6396264,
      name: 'Честно',
      alternativeName: null,
      type: 'tv-series',
      typeNumber: 2,
      year: 2010,
      description: null,
      shortDescription: null,
      status: null,
      rating: {
        kp: 0,
        imdb: 0,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      votes: {
        kp: 1,
        imdb: 0,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      movieLength: null,
      totalSeriesLength: null,
      seriesLength: null,
      ratingMpaa: null,
      ageRating: null,
      genres: [
        {
          name: 'документальный',
        },
      ],
      countries: [
        {
          name: 'Россия',
        },
      ],
      releaseYears: [
        {
          start: 2010,
          end: null,
        },
      ],
      top10: null,
      top250: null,
      isSeries: true,
      ticketsOnSale: false,
    },
    {
      id: 6396261,
      name: 'Русские сказки',
      alternativeName: null,
      type: 'tv-series',
      typeNumber: 2,
      year: 2011,
      description:
        'Информационно-аналитическая авторская программа главного редактора «Русской Службы Новостей» Сергея Доренко. О событиях недели Доренко рассуждает с гостями студии, экспертами и непосредственными участниками.',
      shortDescription: null,
      status: null,
      rating: {
        kp: 0,
        imdb: 0,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      votes: {
        kp: 1,
        imdb: 0,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      movieLength: null,
      totalSeriesLength: null,
      seriesLength: null,
      ratingMpaa: null,
      ageRating: null,
      genres: [
        {
          name: 'документальный',
        },
      ],
      countries: [
        {
          name: 'Россия',
        },
      ],
      releaseYears: [
        {
          start: 2011,
          end: null,
        },
      ],
      top10: null,
      top250: null,
      isSeries: true,
      ticketsOnSale: false,
    },
    {
      id: 6400253,
      name: 'Другое кино',
      alternativeName: null,
      type: 'tv-series',
      typeNumber: 2,
      year: 2006,
      description: null,
      shortDescription: null,
      status: 'completed',
      rating: {
        kp: 0,
        imdb: 0,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      votes: {
        kp: 2,
        imdb: 0,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      movieLength: null,
      totalSeriesLength: null,
      seriesLength: null,
      ratingMpaa: null,
      ageRating: null,
      genres: [
        {
          name: 'документальный',
        },
        {
          name: 'новости',
        },
      ],
      countries: [
        {
          name: 'Россия',
        },
      ],
      releaseYears: [
        {
          start: 2006,
          end: 2008,
        },
      ],
      top10: null,
      top250: null,
      isSeries: true,
      ticketsOnSale: false,
    },
    {
      id: 6406526,
      name: 'Страна чудес',
      alternativeName: 'Shen lan qi yu wu shuang zhu',
      type: 'animated-series',
      typeNumber: 5,
      year: 2022,
      description: null,
      shortDescription: null,
      status: null,
      rating: {
        kp: 0,
        imdb: 8.7,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      votes: {
        kp: 0,
        imdb: 51,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      movieLength: null,
      totalSeriesLength: null,
      seriesLength: 24,
      ratingMpaa: null,
      ageRating: null,
      poster: {
        url: 'https://image.openmoviedb.com/kinopoisk-images/4486362/f6d3fb3e-8aba-4c44-8b6b-6ffa355b2fa7/orig',
        previewUrl:
          'https://image.openmoviedb.com/kinopoisk-images/4486362/f6d3fb3e-8aba-4c44-8b6b-6ffa355b2fa7/x1000',
      },
      genres: [
        {
          name: 'мультфильм',
        },
        {
          name: 'фэнтези',
        },
        {
          name: 'боевик',
        },
      ],
      countries: [
        {
          name: 'Китай',
        },
      ],
      releaseYears: [
        {
          start: 2022,
          end: null,
        },
      ],
      top10: null,
      top250: null,
      isSeries: true,
      ticketsOnSale: false,
    },
    {
      id: 6403229,
      name: 'Беги',
      alternativeName: null,
      enName: null,
      type: 'movie',
      typeNumber: 1,
      year: null,
      description:
        'Вор-медвежатник Саша проникает в дом, где становится свидетелем преступления: хозяин дома Чернов убил свою жену. Чернов начинает преследовать сбежавшего свидетеля. А Саше тем временем надо успеть приехать на утренник к сыну, ведь от этого зависит будущее его брака, который он всеми силами пытается спасти.',
      shortDescription: null,
      status: 'filming',
      rating: {
        kp: 0,
        imdb: 0,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      votes: {
        kp: 0,
        imdb: 0,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      movieLength: null,
      totalSeriesLength: null,
      seriesLength: null,
      ratingMpaa: null,
      ageRating: null,
      genres: [
        {
          name: 'комедия',
        },
        {
          name: 'криминал',
        },
      ],
      countries: [
        {
          name: 'Россия',
        },
      ],
      top10: null,
      top250: null,
      isSeries: false,
      ticketsOnSale: false,
    },
    {
      id: 6396514,
      name: 'Спасатели',
      alternativeName: null,
      type: 'tv-series',
      typeNumber: 2,
      year: 2009,
      description:
        'Еженедельный информационный проект, рассказывающий о буднях тех, кто посвятил свою жизнь спасению людей, — спасателей и медиков экстренной помощи.',
      shortDescription: null,
      status: null,
      rating: {
        kp: 0,
        imdb: 0,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      votes: {
        kp: 1,
        imdb: 0,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      movieLength: null,
      totalSeriesLength: null,
      seriesLength: null,
      ratingMpaa: null,
      ageRating: null,
      genres: [
        {
          name: 'документальный',
        },
      ],
      countries: [
        {
          name: 'Россия',
        },
      ],
      releaseYears: [
        {
          start: 2009,
          end: null,
        },
      ],
      top10: null,
      top250: null,
      isSeries: true,
      ticketsOnSale: false,
    },
    {
      id: 6396259,
      name: 'Независимое расследование РЕН ТВ',
      alternativeName: null,
      type: 'tv-series',
      typeNumber: 2,
      year: 2011,
      description:
        'Самые резонансные происшествия и преступления сегодняшнего дня. Ведущий сам проводит расследование, озвучивает официальные версии произошедшего и, на основе собранных в ходе программы фактов, предлагает свою версию события.',
      shortDescription: null,
      status: 'completed',
      rating: {
        kp: 0,
        imdb: 0,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      votes: {
        kp: 1,
        imdb: 0,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      movieLength: null,
      totalSeriesLength: null,
      seriesLength: null,
      ratingMpaa: null,
      ageRating: null,
      genres: [
        {
          name: 'документальный',
        },
      ],
      countries: [
        {
          name: 'Россия',
        },
      ],
      releaseYears: [
        {
          start: 2011,
          end: 2012,
        },
      ],
      top10: null,
      top250: null,
      isSeries: true,
      ticketsOnSale: false,
    },
    {
      id: 6396513,
      name: 'ЧП. Обзор за неделю',
      alternativeName: null,
      type: 'tv-series',
      typeNumber: 2,
      year: 2007,
      description: 'Чрезвычайные происшествия недели, громкие истории и криминальные хроники.',
      shortDescription: null,
      status: 'completed',
      rating: {
        kp: 0,
        imdb: 0,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      votes: {
        kp: 1,
        imdb: 0,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      movieLength: null,
      totalSeriesLength: null,
      seriesLength: null,
      ratingMpaa: null,
      ageRating: null,
      genres: [
        {
          name: 'документальный',
        },
      ],
      countries: [
        {
          name: 'Россия',
        },
      ],
      releaseYears: [
        {
          start: 2007,
          end: 2015,
        },
      ],
      top10: null,
      top250: null,
      isSeries: true,
      ticketsOnSale: false,
    },
    {
      id: 6407363,
      name: 'Автосемейка Вилзи',
      alternativeName: null,
      type: 'animated-series',
      typeNumber: 5,
      year: 2022,
      description:
        'Автосемейка Вилзи — счастливая семья автомобилей. Мама и папа Вилзи заняты работой и домом. Младший сын — маленький самосвал Плюмбум — учится у родителей и брата с сестрой всему, что он наблюдает. А погодки — Вруми и Бруми — все время веселятся и спорят друг с другом. Хорошо, что рядом с внуками живет их дедушка — экскаватор Ковш. Он объясняет озорным детям, как правильно себя вести, играть вместе и придумывает интересные уроки для маленького Плюмбума и полезные занятия для двух непоседливых погодков.',
      shortDescription: null,
      status: 'completed',
      rating: {
        kp: 0,
        imdb: 0,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      votes: {
        kp: 1,
        imdb: 0,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      movieLength: null,
      totalSeriesLength: null,
      seriesLength: 10,
      ratingMpaa: null,
      ageRating: 6,
      poster: {
        url: 'https://image.openmoviedb.com/kinopoisk-images/10809116/f5f49d59-f01d-42c2-a675-db55a9d25a3a/orig',
        previewUrl:
          'https://image.openmoviedb.com/kinopoisk-images/10809116/f5f49d59-f01d-42c2-a675-db55a9d25a3a/x1000',
      },
      genres: [
        {
          name: 'мультфильм',
        },
        {
          name: 'детский',
        },
      ],
      countries: [
        {
          name: 'Россия',
        },
      ],
      releaseYears: [
        {
          start: 2022,
          end: 2024,
        },
      ],
      top10: null,
      top250: null,
      isSeries: true,
      ticketsOnSale: false,
    },
    {
      id: 6407219,
      name: 'Здравствуйте, я к Вашим услугам',
      alternativeName: 'Jin pai ke fu Dong Dongen',
      type: 'tv-series',
      typeNumber: 2,
      year: 2023,
      description: null,
      shortDescription: null,
      status: 'completed',
      rating: {
        kp: 0,
        imdb: 7.3,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      votes: {
        kp: 0,
        imdb: 63,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      movieLength: null,
      totalSeriesLength: null,
      seriesLength: 45,
      ratingMpaa: null,
      ageRating: null,
      poster: {
        url: 'https://image.openmoviedb.com/kinopoisk-images/10592371/722bfb0e-765f-42fd-a11e-104cd2b67126/orig',
        previewUrl:
          'https://image.openmoviedb.com/kinopoisk-images/10592371/722bfb0e-765f-42fd-a11e-104cd2b67126/x1000',
      },
      genres: [
        {
          name: 'мелодрама',
        },
        {
          name: 'комедия',
        },
      ],
      countries: [
        {
          name: 'Китай',
        },
      ],
      releaseYears: [
        {
          start: 2023,
          end: 2023,
        },
      ],
      top10: null,
      top250: null,
      isSeries: true,
      ticketsOnSale: false,
    },
    {
      id: 639464,
      name: 'Если',
      alternativeName: 'Kdyby',
      enName: null,
      type: 'movie',
      typeNumber: 1,
      year: 1983,
      description: null,
      shortDescription: null,
      status: null,
      rating: {
        kp: 0,
        imdb: 7.1,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      votes: {
        kp: 0,
        imdb: 15,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      movieLength: 9,
      totalSeriesLength: null,
      seriesLength: null,
      ratingMpaa: null,
      ageRating: null,
      genres: [
        {
          name: 'короткометражка',
        },
        {
          name: 'музыка',
        },
      ],
      countries: [
        {
          name: 'Чехословакия',
        },
      ],
      top10: null,
      top250: null,
      isSeries: false,
      ticketsOnSale: false,
    },
    {
      id: 6396392,
      name: 'Вечно молодой. Две жизни Сергея Бодрова',
      alternativeName: null,
      enName: null,
      type: 'movie',
      typeNumber: 1,
      year: 2015,
      description: 'Эксклюзивные интервью коллег Сергея Бодрова.',
      shortDescription: null,
      status: null,
      rating: {
        kp: 0,
        imdb: 0,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      votes: {
        kp: 0,
        imdb: 0,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      movieLength: 39,
      totalSeriesLength: null,
      seriesLength: null,
      ratingMpaa: null,
      ageRating: null,
      genres: [
        {
          name: 'документальный',
        },
        {
          name: 'короткометражка',
        },
      ],
      countries: [
        {
          name: 'Россия',
        },
      ],
      top10: null,
      top250: null,
      isSeries: false,
      ticketsOnSale: false,
    },
    {
      id: 6404004,
      name: 'Бесконечное счастье',
      alternativeName: 'The Infinite Happiness',
      enName: null,
      type: 'movie',
      typeNumber: 1,
      year: 2015,
      description:
        'Недалеко от Копенгагена по проекту архитектора Бьярке Ингельса был построен необычный белый дом. Здесь живут дворник и почтальон, коровы и овцы, большие семьи и одинокие чудаки.',
      shortDescription: null,
      status: null,
      rating: {
        kp: 0,
        imdb: 7.7,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      votes: {
        kp: 0,
        imdb: 54,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      movieLength: 85,
      totalSeriesLength: null,
      seriesLength: null,
      ratingMpaa: null,
      ageRating: 18,
      poster: {
        url: 'https://image.openmoviedb.com/kinopoisk-images/10812607/3319f993-8b62-4f14-836c-7b3890357a6a/orig',
        previewUrl:
          'https://image.openmoviedb.com/kinopoisk-images/10812607/3319f993-8b62-4f14-836c-7b3890357a6a/x1000',
      },
      genres: [
        {
          name: 'документальный',
        },
      ],
      countries: [
        {
          name: 'Франция',
        },
        {
          name: 'Дания',
        },
      ],
      top10: null,
      top250: null,
      isSeries: false,
      ticketsOnSale: false,
    },
    {
      id: 1323917,
      name: 'Бумажный журавлик',
      alternativeName: 'Hana no orizurugaki',
      enName: null,
      type: 'movie',
      typeNumber: 1,
      year: 1962,
      description: null,
      shortDescription: null,
      status: null,
      rating: {
        kp: 0,
        imdb: 0,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      votes: {
        kp: 0,
        imdb: 0,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      movieLength: 87,
      totalSeriesLength: null,
      seriesLength: null,
      ratingMpaa: null,
      ageRating: null,
      genres: [
        {
          name: 'драма',
        },
      ],
      countries: [
        {
          name: 'Япония',
        },
      ],
      top10: null,
      top250: null,
      isSeries: false,
      ticketsOnSale: false,
    },
    {
      id: 816306,
      name: 'Принцесса',
      alternativeName: 'Princesse',
      enName: null,
      type: 'cartoon',
      typeNumber: 3,
      year: 2010,
      description: null,
      shortDescription: null,
      status: null,
      rating: {
        kp: 0,
        imdb: 0,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      votes: {
        kp: 0,
        imdb: 0,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      movieLength: 11,
      totalSeriesLength: null,
      seriesLength: null,
      ratingMpaa: null,
      ageRating: null,
      genres: [
        {
          name: 'короткометражка',
        },
        {
          name: 'мультфильм',
        },
      ],
      countries: [
        {
          name: 'Канада',
        },
      ],
      top10: null,
      top250: null,
      isSeries: false,
      ticketsOnSale: false,
    },
    {
      id: 6404005,
      name: 'Помероль, Херцог и де Мёрон',
      alternativeName: 'Pomerol, Herzog & de Meuron',
      enName: null,
      type: 'movie',
      typeNumber: 1,
      year: 2013,
      description:
        'Французское винодельческое хозяйство Петрюс расположено в Бордо. Недавно винный склад и дегустационный зал были перестроены архитектурным бюро Херцог и де Мёрон, и теперь виноделы привыкают работать и праздновать в новых условиях.',
      shortDescription: null,
      status: null,
      rating: {
        kp: 0,
        imdb: 9.1,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      votes: {
        kp: 0,
        imdb: 11,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      movieLength: 51,
      totalSeriesLength: null,
      seriesLength: null,
      ratingMpaa: null,
      ageRating: 16,
      poster: {
        url: 'https://image.openmoviedb.com/kinopoisk-images/4483445/39bac3a0-e667-4521-a446-8c50bc7e2af6/orig',
        previewUrl:
          'https://image.openmoviedb.com/kinopoisk-images/4483445/39bac3a0-e667-4521-a446-8c50bc7e2af6/x1000',
      },
      genres: [
        {
          name: 'документальный',
        },
      ],
      countries: [
        {
          name: 'Франция',
        },
      ],
      top10: null,
      top250: null,
      isSeries: false,
      ticketsOnSale: false,
    },
    {
      id: 6396265,
      name: 'Виктор Цой. Рождение легенды',
      alternativeName: null,
      enName: null,
      type: 'movie',
      typeNumber: 1,
      year: 2015,
      description: 'Эксклюзивные интервью друзей и известных поклонников Виктора Цоя.',
      shortDescription: null,
      status: null,
      rating: {
        kp: 0,
        imdb: 0,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      votes: {
        kp: 1,
        imdb: 0,
        filmCritics: 0,
        russianFilmCritics: 0,
        await: 0,
      },
      movieLength: 39,
      totalSeriesLength: null,
      seriesLength: null,
      ratingMpaa: null,
      ageRating: null,
      genres: [
        {
          name: 'документальный',
        },
        {
          name: 'короткометражка',
        },
      ],
      countries: [
        {
          name: 'Россия',
        },
      ],
      top10: null,
      top250: null,
      isSeries: false,
      ticketsOnSale: false,
    },
  ],
  total: 304600,
  limit: 250,
  page: 1,
  pages: 1219,
};
